django_omise/urls.py
from django.urls import path, include

from .views import (
    omise_webhook_view,
    charge_status_json,
    ManagePaymentMethodsView,
    PaymentMethodDeleteView,
    OmiseReturnURIView,
    CheckoutView,
    PromptpayCheckoutView,
    OmiseAccountAndCapabilityJsonView,
)

from .admin_views import IssueRefundView

app_name = "django_omise"

urlpatterns = [
    path(
        "omise_account/",
        OmiseAccountAndCapabilityJsonView.as_view(),
        name="omise_account",
    ),
    path("checkout/", CheckoutView.as_view(), name="checkout"),
    path("return/<uuid:uid>/", OmiseReturnURIView.as_view(), name="return_uri"),
    path("webhook/", omise_webhook_view, name="webhook"),
    path(
        "promptpay_checkout/<pk>/",
        PromptpayCheckoutView.as_view(),
        name="promptpay_checkout",
    ),
    path("charge_status/", charge_status_json, name="charge_status_json"),
    path(
        "payment_methods/",
        include(
            [
                path(
                    "",
                    ManagePaymentMethodsView.as_view(),
                    name="manage_payment_methods",
                ),
                path(
                    "delete/<pk>/",
                    PaymentMethodDeleteView.as_view(),
                    name="delete_payment_method",
                ),
            ]
        ),
    ),
    path(
        "custom_model_action/",
        include(
            [
                path(
                    "charge/",
                    include(
                        [
                            path(
                                "<pk>/refund/",
                                IssueRefundView.as_view(),
                                name="issue_refund",
                            )
                        ]
                    ),
                )
            ]
        ),
    ),
]

django_omise/models/base.py
from __future__ import annotations

import uuid
from django.apps import apps
from django.db import models

from django_omise.omise import omise
from django_omise.utils.core_utils import (
    update_or_create_from_omise_object,
)

from django.utils.translation import gettext_lazy as _

from typing import Optional, Dict
from .managers import DeletableManager

from typing import List


class OmiseMetadata(models.Model):

    metadata = models.JSONField(
        default=dict,
        blank=True,
        help_text=_("Custom metadata for this object."),
    )

    def set_metadata(self, metadata: Optional[Dict] = None) -> "OmiseBaseModel":
        """
        Set the object's medata both on Omise and the Django object.

        :params metadata: A dictionary for medatada

        :returns: Currenct object.
        """

        if metadata is None:
            metadata = {}

        omise_object = self.omise_class.retrieve(self.id)
        omise_object.update(metadata=metadata)

        self.metadata = metadata
        self.save()

        return self

    class Meta:
        abstract = True


class OmiseBaseModel(models.Model):

    id = models.CharField(max_length=255, primary_key=True)
    livemode = models.BooleanField()
    data = models.JSONField(default=dict, blank=True)

    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    uid = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)

    NON_DEFAULT_FIELDS = [
        "id",
        "date_created",
        "date_updated",
        "data",
        "uid",
    ]

    def __str__(self):
        return f"Omise{self.__class__.__name__}: {self.id}"

    class Meta:
        abstract = True
        ordering = [
            "-date_created",
        ]

    def get_omise_object(self) -> omise.Base:
        """Fetch the object from Omise's server."""
        return self.omise_class.retrieve(self.id)

    def reload_from_omise(
        self, ignore_fields: Optional[List[str]] = None
    ) -> OmiseBaseModel:
        """
        Reload the data from Omise's server and return the saved object

        :param ignore_fields: List of field names to ignore.
        """
        omise_object = self.omise_class.retrieve(self.id)
        return self.__class__.update_or_create_from_omise_object(
            omise_object=omise_object,
            ignore_fields=ignore_fields,
        )

    @classmethod
    def update_or_create_from_omise_object(
        cls,
        omise_object: omise.Base,
        ignore_fields: Optional[List[str]] = None,
        uid: Optional[uuid.UUID] = None,
    ) -> OmiseBaseModel:
        """
        Update existing charge or create a new charge from Omise Charge object.

        :param omise_object: An instance of Omise object
        :param ignore_fields optional: List of field names to ignore
        :param uuid optional: A unique id for new object.

        :returns: An instance of current class
        """
        defaults = cls.build_defaults_from_omise_object(
            omise_object=omise_object,
            ignore_fields=ignore_fields,
            uid=uid,
        )

        new_object, created = cls.objects.update_or_create(
            pk=omise_object.id,
            defaults=defaults,
        )

        return new_object

    @classmethod
    def build_defaults_from_omise_object(
        cls,
        omise_object: omise.Base,
        ignore_fields: Optional[List[str]] = None,
        uid: Optional[uuid.UUID] = None,
    ) -> Dict:
        """
        Create a dictionary of fields and values to use in objects.update_or_create method.

        :param omise_object: Any of the object from omise package. e.g. omise.Charge, omise.Customer, omise.Card
        :param ignore_fields: List of field names as a string to ignore.
        :param uid: The uid of the object. If this is not specify, a new uid will be created for the object.

        :returns: Dictionary of fields and values as keys and values
        """
        fields = cls.get_field_names(
            ignore_fields=ignore_fields,
        )

        fields = [field for field in fields if field.name not in cls.NON_DEFAULT_FIELDS]

        defaults = {}

        if uid is not None:
            defaults["uid"] = uid

        for field in fields:
            if field.name == "metadata":
                defaults["metadata"] = getattr(
                    omise_object,
                    field.name,
                ).__dict__.get("_attributes")
                continue

            if callable(getattr(omise_object, field.name, None)):
                continue

            if (
                getattr(getattr(omise_object, field.name, None), "object", None)
                == "list"
            ):
                values = getattr(omise_object, field.name)
                for value in values:
                    update_or_create_from_omise_object(omise_object=value)
                continue

            if type(field) in [models.ForeignKey, models.OneToOneField]:
                value = getattr(omise_object, field.name, None)

                if value is None or type(value) is str:
                    defaults[f"{field.name}_id"] = value
                else:

                    new_object = update_or_create_from_omise_object(omise_object=value)

                    defaults[field.name] = new_object

                continue

            if (
                type(field) in [models.TextField, models.CharField]
                and getattr(omise_object, field.name, None) is None
            ):
                defaults[field.name] = ""
                continue

            if (
                getattr(omise_object, field.name, None) is None
                and field.null == False
                and field.default
            ):
                defaults[field.name] = field.default()
                continue

            defaults[field.name] = getattr(omise_object, field.name, None)

        return defaults

    @classmethod
    def get_field_names(
        cls,
        ignore_fields: Optional[List[str]] = None,
    ) -> List[models.fields.Field]:
        """
        Get a list of fields of the class.

        :param ignore_fields: List of field names as a string to ignore.
        :param additional_fields: List of field names as tuple of field name and field type
        """
        ignore_fields = [] if ignore_fields is None else ignore_fields

        fields = [
            field for field in cls._meta.get_fields() if field.name not in ignore_fields
        ]

        return fields


class OmiseDeletableModel(models.Model):
    deleted = models.BooleanField(
        default=False,
        help_text=_("Whether this object is marked as deleted on Omise's server"),
    )

    objects = DeletableManager()

    class Meta:
        abstract = True

django_omise/templates/django_omise/account_and_compatibility.html
{% extends 'django_omise/base.html' %}
{% load i18n %}

{% block head_title %}{% trans 'Omise Account and Capability' %}{% endblock %}

{% block content %}
<div class="container mx-auto py-6">
    <h1 class="text-xl mb-4">{% trans 'Omise account and capability' %}</h1>
    <div class="p-4 border rounded-lg mb-4 text-sm">
        <h2 class="text-xl mb-4"><a href="https://www.omise.co/account-api" target="_blank" class="text-blue-500">Account</a></h2>
        <ul>
            <li class="mb-2">id: <strong>{{ account.id }}</strong></li>
            <li class="mb-2">team: <strong>{{ account.team }}</strong></li>
            <li class="mb-2">livemode: <strong>{{ account.livemode }}</strong></li>
            <li class="mb-2">country: <strong>{{ account.country }}</strong></li>
            <li class="mb-2">currency: <strong>{{ account.currency }}</strong></li>
            <li class="mb-2">email: <strong>{{ account.email }}</strong></li>
            <li class="mb-2">created_at: <strong>{{ account.created_at }}</strong></li>
            <li class="mb-2">supported_currencies: <strong>{{ account.supported_currencies|join:", " }}</strong></li>
            <li class="mb-2">api_version: <strong>{{ account.api_version }}</strong></li>
            <li class="mb-2">auto_activate_recipients: <strong>{{ account.auto_activate_recipients }}</strong></li>
            <li class="mb-2">chain_enabled: <strong>{{ account.chain_enabled }}</strong></li>
            <li class="mb-2">zero_interest_installments: <strong>{{ account.zero_interest_installments }}</strong></li>
            <li class="mb-2">chain_return_uri: <strong>{{ account.chain_return_uri }}</strong></li>
            <li class="mb-2">webhook_uri: <strong>{{ account.webhook_uri }}</strong></li>
            <li class="mb-2">metadata_export_keys: <strong>{{ account.metadata_export_keys }}</strong></li>
            <li class="mb-2">last_updated_api_version : <strong>{{ account.last_updated_api_version }}</strong></li>
        </ul>
    </div>
    <div class="p-4 border rounded-lg mb-4 text-sm">
        <h2 class="text-xl mb-4"><a href="https://www.omise.co/capability-api" class="text-blue-500" target="_blank">Capability</a></h2>
        <ul>
            <li class="mb-2">banks: <strong>{{ capability.banks|join:", " }}</strong></li>
            <li class="mb-2">tokenization_methods: <strong>{{ capability.tokenization_methods|join:", " }}</strong></li>
            <li class="mb-2">country: <strong>{{ capability.country}}</strong></li>
            <li class="mb-2">zero_interest_installments: <strong>{{ capability.zero_interest_installments }}</strong></li>
            <li class="mb-2">
                <p class="mb-2">payment_methods</p>
                <ul>
                    {% for payment_method in capability.payment_methods %}
                        <li class="ml-4 mb-4">
                            <p>
                                name: <strong>{{ payment_method.name }}</strong><br />
                                currencies: <strong>{{ payment_method.currencies|join:", " }}</strong><br />
                                {% if payment_method.card_brands %}
                                card_brands: <strong>{{ payment_method.card_brands|join:", "|default_if_none:"-" }}</strong><br />
                                {% endif %}
                                
                                {% if payment_method.installment_terms %}
                                installment_terms: <strong>{{ payment_method.installment_terms|join:", "|default_if_none:"-" }}</strong><br />
                                {% endif %}

                                {% if payment_method.banks %}
                                banks: <strong>{{ payment_method.banks|join:", " }}</strong><br />
                                {% endif %}
                            </p>
                        </li>
                    {% endfor %}
                </ul>
            </li>
        </ul>
    </div>
</div>
{% endblock %}

django_omise/templates/django_omise/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>{% block head_title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'django_omise/css/tailwind_output.css' %}">
    {% block extra_head %}
    {% endblock %}
  </head>
  <body>
    {% block body %}

    {% if messages %}
    <div>
      <ul>
        {% for message in messages %}
        <li>{{message}}</li>
        {% endfor %}
      </ul>
    </div>
    {% endif %}

    {% block content %}
    {% endblock %}

    {% endblock %}

    {% block extra_body %}
    {% endblock %}
  </body>
</html>

django_omise/templates/django_omise/card_confirm_delete.html
{% extends 'django_omise/base.html' %}
{% load i18n static %}

{% block head_title %}{% trans "Delete Payment Method" %}{% endblock %}

{% block content %}
<div>
    <h1>{% trans 'Delete Card' %}</h1>

    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete the card that ends with {{ object.last_digits }}</p>
        <a href="{% url 'django_omise:manage_payment_methods' %}">{% trans 'Cancel' %}</a>
        <button id="submit_button" type="submit" name="remove_card">{% trans "Delete card" %}</button>
    </form>

</div>

{% endblock %}

django_omise/templates/django_omise/checkout.html
{% extends 'django_omise/base.html' %}
{% load i18n %}
{% block head_title %}Checkout{% endblock %}

{% block content %}
<form action="" method="post" id="checkout">{% csrf_token %}

    {{ form.has_error }}
    {{ form.non_field_errors }}

    {% for hidden in form.hidden_fields %}
        {{ hidden }}
    {% endfor %}

    {% for choice in form.payment_method %}
        <div>
            <div>
                {{ choice.tag }}
                <label for="{{ choice.id_for_label }}">{{ choice.choice_label }}</label>

                {% if choice.data.value == 'old_card' %}
                <div class="payment_options_container ml-4 hidden">

                    {{ form.card.errors }}
                    {{ form.card }}

                </div>
                {% elif choice.data.value == 'new_card' %}
                <div class="payment_options_container ml-4 hidden">

                    <div id="token_errors" class="p-4 bg-red-300 hidden mb-4">
                        {% for hidden_field in form.hidden_fields %}
                            {% for error in  hidden_field.errors %}
                                {{ error }}<br />
                            {% endfor %}
                        {% endfor %}
                    </div>
                    {% for field in form.new_card_fields %}
                    <div class="mb-2">
                        {{ field.errors }}
                        {{ field.label_tag }}
                        {{ field }}
                    </div>
                    {% endfor %}

                </div>
                {% elif choice.data.value == 'internet_banking' %}
                <div class="payment_options_container ml-4 hidden">
                    {{ form.bank.errors }}
                    {{ form.bank }}
                </div>
                {% elif choice.data.value == 'truemoney_wallet' %}
                <div class="payment_options_container ml-4 hidden">
                    {% for field in form.truemoney_fields %}
                    <div class="mb-2">
                        {{ field.errors }}
                        {{ field.label_tag }}
                        {{ field }}
                    </div>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
        </div>
    {% endfor %}
    <button class="border p-4 mt-4 bg-blue-700 text-white" type="submit" id="submit_button">{% trans 'Make the payment' %}</button>
</form>

{{ form.media }}

{% endblock %}

django_omise/templates/django_omise/manage_payment_methods.html
{% extends 'django_omise/base.html' %}
{% load i18n static %}

{% block head_title %}{% trans "Manage Payment Methods" %}{% endblock %}

{% block content %}
<div>
    <div id="token_errors">
        {% for hidden_field in form.hidden_fields %}
            {% for error in  hidden_field.errors %}
                {{ error }}<br />
            {% endfor %}
        {% endfor %}
    </div>
    <h1>{% trans 'Add new card' %}</h1>

    <form id="checkout" method="post">{% csrf_token %}
        {{ form.as_p }}
        <button id="submit_button" type="submit" name="add_card">{% trans "Add card" %}</button>
    </form>

    {{ form.media }}
</div>

<div>
    {% trans 'Your payment methods' %}
    <ul>
        {% for card in customer.cards.live %}
        <li>XXXX XXXX XXXX {{ card.last_digits }}</li><a href="{% url 'django_omise:delete_payment_method' card.id %}">delete</a>
        {% endfor %}
    </ul>
</div>

{% endblock %}

django_omise/templates/django_omise/promptpay_checkout.html
{% extends 'django_omise/base.html' %}
{% load i18n %}
{% load static %}

{% block head_title %}{% trans 'Promptpay Checkout' %}{% endblock %}

{% block content %}
<div class="bg-gray-200 p-4 min-h-screen">
    <div class="container mx-auto p-4 sm:grid sm:grid-cols-3">
        <div></div>
        <div class="border bg-white rounded-lg p-4 lg:mx-10">
        {% with omise_source=charge.source.get_omise_object %}
            {% if omise_source.charge_status == 'pending' %}

                <h1 class="text-lg mb-4">{% trans 'Complete the payment with the QR code below.' %}</h1>

                <img src="{{ omise_source.scannable_code.image.download_uri }}" alt="Promptpay QR Code" class="border border-gray-200">
                <p class="text-center mt-4">{% trans 'Total' %}: {{ charge.human_amount }} {{ charge.currency }}</p>
            
            {% elif omise_source.charge_status == 'successful' %}

            <h1 class="text-xl">{% trans 'Payment completed' %}</h1>

            {% elif omise_source.charge_status == 'failed' %}

            <h1 class="text-xl">{% trans 'Payment failed' %}</h1>

            {% endif %}

        {% endwith %}
        </div>
        <div></div>

    </div>
</div>

<script>
    const charge = "{{ charge.id }}";
    const chargeStatusUrl = "{% url 'django_omise:charge_status_json' %}";
</script>
<script src="{% static 'django_omise/js/main.js' %}"></script>
<script src="{% static 'django_omise/js/promptpay.js' %}"></script>
{% endblock %}